name: Keep Alive

on:
  schedule:
    - cron: '*/10 7-21 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: |
          for i in {1..5}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.BACKEND_URL }}/api/meta")
            echo "Attempt $i → $STATUS"

            if [ "$STATUS" -eq 200 ]; then
              echo "Success"
              exit 0
            fi

            sleep 5
          done

          echo "Done"
